#!/bin/bash

echo "Enter BIP-39 mnemonic: "
read HDWALLET_MNEMONIC
echo "Enter target network name (as defined in truffle.js): "
read NETWORK
HDWALLET_MNEMONIC=$HDWALLET_MNEMONIC node_modules/.bin/truffle migrate --network $NETWORK
